# Generated by Django 5.1 on 2024-08-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_insurance_payment_and_more'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedule', to='booking.booking'),
        ),
        migrations.DeleteModel(
            name='DeliveryDocument',
        ),
    ]
