# Generated by Django 5.1 on 2024-08-30 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_insurance_payment_and_more'),
        ('delivery', '0002_alter_deliveryhistory_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhistory',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_histories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryschedule',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryhistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='deliveryschedule',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
