# Generated by Django 5.1 on 2024-11-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryhistory_client_deliveryschedule_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryhistory',
            name='delivery_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
