# Generated by Django 5.1 on 2025-01-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_insurance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='image',
            field=models.ImageField(default='trucks/service-3.jpg', upload_to='trucks/'),
        ),
    ]
